name: 문서 작업
description: README, 가이드 문서 등의 작성/수정 요청
title: "[Docs] "
labels: ["docs"]
body:
  - type: input
    id: summary
    attributes:
      label: 문서 주제
      placeholder: 문서 주제 내용
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: 작업 내용
      placeholder: |
        - (예시) endpoint 설명 추가  
        - 
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 작업 대상
    placeholder: |
      - [ ] (예시) README.md
      - [ ] 

  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - 낮음
        - 보통
        - 높음
        - 치명적