name: 문서 작업
description: README, 가이드 문서 등의 작성/수정 요청
title: "[Docs] "
labels: ["docs"]
body:
  - type: input
    id: summary
    attributes:
      label: 문서 주제
      placeholder: API 사용 가이드 문서 추가
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: 작업 내용
      placeholder: |
        - endpoint 설명 추가  
        - request/response 예시 작성  
        - 인증 방식 설명
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 작업 대상
      options:
        - label: README.md
        - label: API 명세 문서
        - label: 내부 위키
        - label: 오류 메시지 설명 추가