name: 기능 요청
description: 새로운 기능을 제안해주세요.
title: "[Feature] "
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: 기능 요약
      placeholder: 기능 요약 내용
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 어떤 상황에서 필요한 기능이고 어떻게 동작해야 하는지 설명
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 작업 항목
      description: 이 기능을 위해 필요한 작업들을 체크
      placeholder: |
        - [ ] (예시) API 엔드포인트 생성
        - [ ] 

  - type: textarea
    id: etc
    attributes:
      label: 참고자료
      description: 관련 문서나 URL이 있다면 추가

  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - 낮음
        - 보통
        - 높음
        - 치명적