name: 기능 요청
description: 새로운 기능을 제안해주세요.
title: "[Feature] "
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: 기능 요약
      placeholder: 사용자 알림 기능 추가
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 어떤 상황에서 필요한 기능이고 어떻게 동작해야 하는지 설명해주세요.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 작업 항목
      description: 이 기능을 위해 필요한 작업들을 체크하세요.
      options:
        - label: API 엔드포인트 생성
        - label: DB 모델 설계
        - label: 프론트 UI 설계
        - label: 테스트 코드 작성
        - label: 문서 작성

  - type: textarea
    id: etc
    attributes:
      label: 참고자료
      description: 관련 문서나 URL이 있다면 추가해주세요.