name: 리팩토링
description: 구조 개선 또는 코드 정리를 제안합니다.
title: "[Refactor] "
labels: ["refactor"]
body:
  - type: input
    id: summary
    attributes:
      label: 리팩토링 대상
      placeholder: auth 모듈 내 중복 로직 제거
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 리팩토링 이유
      description: 현재 구조의 문제점이나 개선 목적을 설명해주세요.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 리팩토링 항목
      options:
        - label: 중복 코드 제거
        - label: 함수 분리
        - label: 네이밍 개선
        - label: 성능 최적화
        - label: 유닛 테스트 영향 확인