name: 리팩토링
description: 구조 개선 또는 코드 정리를 제안합니다.
title: "[Refactor] "
labels: ["refactor"]
body:
  - type: input
    id: summary
    attributes:
      label: 리팩토링 대상
      placeholder: 리팩토링 대상
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 리팩토링 이유
      description: 현재 구조의 문제점이나 개선 목적을 설명
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 리팩토링 항목
      placeholder: |
        - [ ] (예시) 중복 코드 제거
        - [ ] 

  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - 낮음
        - 보통
        - 높음
        - 치명적