name: 일반 작업
description: 일반적인 작업 요청 또는 할 일 등록
title: "[Task] "
labels: ["task"]
body:
  - type: input
    id: summary
    attributes:
      label: 작업 요약
      placeholder: 작업 요약 내용
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 할 일 목록
      placeholder: |
        - (예시) 00 테이블 생성
        -   
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 적용 범위
      placeholder: |
        - [ ] (예시) DDL 작성
        - [ ] 

  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - 낮음
        - 보통
        - 높음
        - 치명적