name: 일반 작업
description: 일반적인 작업 요청 또는 할 일 등록
title: "[Task] "
labels: ["task"]
body:
  - type: input
    id: summary
    attributes:
      label: 작업 요약
      placeholder: 프로젝트 CI 설정 적용
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 할 일 목록
      placeholder: |
        - GitHub Actions 생성  
        - 테스트 명령 추가  
        - PR 트리거 연결
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 적용 범위
      options:
        - label: CI/CD
        - label: Lint/Format
        - label: Git hook
        - label: 프로젝트 구조 변경