name: 테스트 케이스 작성
description: 테스트 코드 추가 또는 보완 요청
title: "[Test] "
labels: ["test"]
body:
  - type: input
    id: target
    attributes:
      label: 테스트 대상
      placeholder: 테스트 대상
    validations:
      required: true

  - type: checkboxes
    id: types
    attributes:
      label: 테스트 종류
      options:
        - label: 단위 테스트
        - label: 통합 테스트
        - label: 모킹 테스트
        - label: 예외 케이스 테스트
        - label: 기타

  - type: textarea
    id: details
    attributes:
      label: 상세 설명
      description: 어떤 시나리오를 테스트해야 하는지 작성
  
  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - 낮음
        - 보통
        - 높음
        - 치명적